### ISSUE TITLE
PuppetDB can deadlock with Puppet

### ISSUE THREAD

**Issue by luksi1** [luksi1/docker-foreman#3]
There are cases where PuppetDB will crash as it can't get it's node information from Puppet. This almost always occurs on a new installation, as the node information is already cached on a running instance.

**Comment by seffyroff** [comment]
Perhaps an init environment with Puppet+puppetDB in the same container to seed the cache could run once then hand off to the correct separate service containers?  Or perhaps there's a MORE *Puppet* way of doing this?

**Comment by luksi1** [comment]
Resolved in 5a2fccd.
