### ISSUE TITLE
The Puppet Container depends on iproute2

### ISSUE THREAD

**Issue by seffyroff** [luksi1/docker-foreman#6]
The docker entrypoint for Puppet uses ip, which is not installed in the image by the Dockerfile:

https://github.com/luksi1/docker-foreman/blob/93cc915a171898c231730e5e9bf9a448d22cdc2e/puppet/docker-entrypoint.sh#L17

I've added this in my fork, and will PR it after some additional testing.

**Comment by luksi1** [comment]
Closed. See #7.
